### ISSUE TITLE
Distance, time_diff, speed functionality already provided by UvA-BiTS DB

### ISSUE THREAD

**Issue by peterdesmet** [inbo/gulltracking#15]
The UvA-BiTS DB has a function:

```sql
select * from gps.get_uvagps_track_speed(5326, '2016-06-01 18:00', '2016-06-01 19:00')
```

Which returns:

device_info_serial | date_time | latitude | longitude | distance | interval | speed | direction
--- | --- | --- | --- | --- | --- | --- | ---
5326 | 2016-06-01 18:07:36 | 51.348188800000003 | 3.1729379999999998 | \N | \N | \N | \N
5326 | 2016-06-01 18:29:10 | 51.348087999999997 | 3.1728736999999998 | 12.06531058575392 | 00:21:34 | 0.0093240421837356424 | 201.72344513617824
5326 | 2016-06-01 18:51:06 | 51.348262400000003 | 3.1731264000000001 | 26.154833184897118 | 00:21:56 | 0.019874493301593556 | 42.14516668347823

With:

> Distances and heading are calculated with spherical correction with the Haversine formula.

We have:

device_info_serial | date_time | latitude | longitude | calc_distance_diff | calc_time_diff | calc_speed_2d | direction
--- | --- | --- | --- | --- | --- | --- | ---
5326 | 2016-06-01T18:07:36Z | 51.3481888 | 3.172938 | NA | NA | NA | **-124.679717701416**
5326 | 2016-06-01T18:29:10Z | 51.348088 | 3.1728737 | 12.07**8892306822** | 1294 | 0.0093**3453810419008** | **-133.425670193646**
5326 | 2016-06-01T18:51:06Z | 51.3482624 | 3.1731264 | 26.1**841032677065** | 1316 | 0.0198**96735005856** | **-54.5015299912165**

Difference (indicated in bold) are small, so we can replace:

* calc_distance_diff → distance
* calc_time_diff → interval (expressed as hh:mm:ss)
* calc_speed_2d → speed
* direction → **seems to be a different kind of direction**

**Comment by peterdesmet** [comment]
@Wouter-Vansteelant are you familiar with difference in **direction** returned by `gps.get_uvagps_track_speed` (201.72344513617824) vs what is available in `ee_tracking_speed_limited` (-133.425670193646)

**Comment by Wouter-Vansteelant** [comment]
@peterdesmet the former is a trajectory speed and direction, which seems to be calculated from the previous to the current point, given that the first value in the example above is NA. I usually do those calculations in R with homemade formulas. The direction and speed values in the  table tracking_speed_limited are instantaneous measurements by GPS.  

I have not used instantaneous speed very much but both values are useful, sometimes in combination. For example, when a soaring bird is climbing in a thermal, the trajectory speed will be low because there is little horizontal displacement, but instantaneous speed will be fairly high, as the bird is flying at a fairly typical air speed. The ratio of the two speed measurements can then help to distinguish circle soaring from straight gliding/flapping flight.

**Comment by peterdesmet** [comment]
Aha, so:

1. get_uvagps_track_speed.speed = speed based on time/distance with previous fix
2. tracking_speed_limited.speed_2d = instantaneous speed measured by GPS
3. get_uvagps_track_speed.direction = degrees from north if we draw a line between previous fix and current one??
4. tracking_speed_limited.direction = instantaneous heading measured by GPS

In that case, I would say for data publication:

1. Only useful to drop points above 120km/h
2. Useful, but call it `air_speed`
3. Not very useful: don't include
4. Useful: is the heading of the bird as it was flying

What do you think?

**Comment by Wouter-Vansteelant** [comment]
Hey Peter,

response hieronder in rood

Aha, so:

   1. get_uvagps_track_speed.speed = speed based on time/distance with
   previous fix
   *Yes*
   2. tracking_speed_limited.speed_2d = instantaneous speed measured by GPS
   *Yes*
   3. get_uvagps_track_speed.direction = degrees from north if we draw a
   line between previous fix and current one??
   *Yes*
   4. tracking_speed_limited.direction = instantaneous heading measured by
   GPS
   *Almost. Its the instantaneous direction. To calculate heading, meaning:
   the direction the bird is facing towards, you still need to correct for
   wind influences. *

In that case, I would say for data publication:

   1. Only useful to drop points above 120km/h
   *I use trajectory speeds all the time. Applicability very much depends
   on resolution of data and question at hand. Potenially very useful. I tend
   to calculate speeds from point i to i+1 instead of from i-1 to i or the
   average of the two, but all three can be valid approaches*
   2. Useful, but call it air_speed
   *No. I know I used this word in my last email but is misleading to use
   this. Calculating airspeed requires information on wind speed and
   direction. Instantaneous measurements are also prone to high errors, I
   think depending on the nr of satellites used and time interval between
   observations. In most of my research so far instantaneous speed has been
   less useful to me than trajectory speed. But that I would keep both in
   dataset as they are both potentially useful.*
   3. Not very useful: don't include
   *For similar reasons as mentioned above for speed, trajectory statistics
   are very useful too. *
   4. Useful: is the heading of the bird as it was flying
   *See above. This is not entirely true. Beyond the complication of
   accounting for atmospheric flow, the extent to which flow influences the
   birds movement relative to the geographical grid depends on the birds
   orientation strategy relative to flow. For that reason the calculation of
   heading is giving a lot of researchers a headache ;)*

**Comment by peterdesmet** [comment]
Ok thanks, than I just need to know how to call these 4 fields. :-)

**Comment by Wouter-Vansteelant** [comment]
suggestion:

forward trajectory speed (from i to i +1): spd.tf
backward trajectory speed (from i to i-1): spd.tb
mean trajectory speed (average of above).  spd.tm
instantaneous speed: spd.i

analagous for direction (dir)

**Comment by peterdesmet** [comment]
Hi @Wouter-Vansteelant , just had a workshop on standardizing tracking data to Darwin Core (the standard used for biodiversity data and the one we use), which means I can pick up the publication of the WMH data again.

The properties discussed above won't be included as fields in a GPS fix record (the fields you can use are defined by Darwin Core), but we can link any measurement to the GPS fix in a separate table:

```
gps_fix_1: lat, long, date_time, ...
gps_fix_2: lat, long, date_time, ...

measurement linked to gps_fix_1: heading
measurement linked to gps_fix_1: speed
measurement linked to gps_fix_1: distance
measurement linked to gps_fix_2: heading
measurement linked to gps_fix_2: speed
measurement linked to gps_fix_2: distance
```

I would like to keep the number of measurements to a minimum set of useful ones, that cannot be derived from the gps_fix data or are hard to calculate. From the discussion above, I would say:

1. interval between i to i-1: fairly easy to calculate, but handy to have it ready **include?**
2. distance between i to i-1: not so straightforward to calculate, **include**
3. speed from i to i-1: can be calculated using 1 and 2, do not include
4. speed from i to i+1: can be calculated using 1 and 2, but hanging it to the next record
5. calculated heading (degrees from north): not so straightforward to calculate, **include**
5. instantaneous speed measured by device: cannot be derived, **include**
6. instantaneous direction measured by device: cannot be derived, **include**. Not sure how to call this.

What do you think?

**Comment by peterdesmet** [comment]
This applies to the [BirdTrackingEtl](https://github.com/inbo/gulltracking/releases/tag/bt-etl) version of the package, which we no longer maintain. Closing with `wontfix`.
